name: Check for Type Errors

on:
  push: # (or pull requests)
    paths:
      - '.github/workflows/**'
      - '**.php'
      - 'app/**'
      - 'tests/**'
      - 'phpunit.xml'
      - 'composer.json'
      - 'composer.lock'
      - 'resources/**'
      - '.prettierrc.json'

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies 🔧
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Static Analysis
        run: vendor/bin/psalm --no-cache
